### ISSUE TITLE
KeyError on search and library scan

### ISSUE THREAD

**Issue by Natureshadow** [plintx/mopidy-radionet#5] opened 2020-11-15 11:28 UTC
After installing Mopidy-Radionet and listening to some streams yesterday, today it stopped working without any obvious change:

```plain
Nov 15 11:26:46 kobel mopidy[50371]: Traceback (most recent call last):
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._handle_receive(envelope.message)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 307, in _handle_receive
Nov 15 11:26:46 kobel mopidy[50371]:     return self.on_receive(message)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/network.py", line 443, in on_receive
Nov 15 11:26:46 kobel mopidy[50371]:     self.on_line_received(line)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/session.py", line 32, in on_line_received
Nov 15 11:26:46 kobel mopidy[50371]:     response = self.dispatcher.handle_request(line)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 46, in handle_request
Nov 15 11:26:46 kobel mopidy[50371]:     return self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 77, in _catch_mpd_ack_errors_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 87, in _authenticate_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 106, in _command_list_filter
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 139, in _idle_filter
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 152, in _add_ok_filter
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._call_next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 69, in _call_next_filter
Nov 15 11:26:46 kobel mopidy[50371]:     return next_filter(request, response, filter_chain)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 164, in _call_handler_filter
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._format_response(self._call_handler(request))
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/dispatcher.py", line 178, in _call_handler
Nov 15 11:26:46 kobel mopidy[50371]:     return protocol.commands.call(tokens, context=self.context)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/__init__.py", line 212, in call
Nov 15 11:26:46 kobel mopidy[50371]:     return self.handlers[tokens[0]](context, *tokens[1:])
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/__init__.py", line 170, in validate
Nov 15 11:26:46 kobel mopidy[50371]:     return func(*args, **kwargs)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/lib/python3/dist-packages/mopidy_mpd/protocol/music_db.py", line 145, in find
Nov 15 11:26:46 kobel mopidy[50371]:     results = context.core.library.search(query=query, exact=True).get()
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_threading.py", line 45, in get
Nov 15 11:26:46 kobel mopidy[50371]:     _compat.reraise(*self._data['exc_info'])
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Nov 15 11:26:46 kobel mopidy[50371]:     raise value
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._handle_receive(envelope.message)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Nov 15 11:26:46 kobel mopidy[50371]:     return callee(*message.args, **message.kwargs)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/mopidy/core/library.py", line 316, in search
Nov 15 11:26:46 kobel mopidy[50371]:     result = future.get()
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_threading.py", line 45, in get
Nov 15 11:26:46 kobel mopidy[50371]:     _compat.reraise(*self._data['exc_info'])
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Nov 15 11:26:46 kobel mopidy[50371]:     raise value
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Nov 15 11:26:46 kobel mopidy[50371]:     response = self._handle_receive(envelope.message)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Nov 15 11:26:46 kobel mopidy[50371]:     return callee(*message.args, **message.kwargs)
Nov 15 11:26:46 kobel mopidy[50371]:   File "/usr/local/lib/python3.8/dist-packages/mopidy_radionet/library.py", line 83, in search
Nov 15 11:26:46 kobel mopidy[50371]:     self.backend.radionet.do_search(' '.join(query['any']))
Nov 15 11:26:46 kobel mopidy[50371]: KeyError: 'any'
```

This happens when I search or browse my library.

**Comment by gemolnar79** [comment] 2020-12-12 10:56
I also have a connectivity issue to Radio.net: the API seems changed.
The module uses a JS variable from the homepage source that has an invalid value:
`apiPrefix: 'https://undefined/info/v2',`
This must be the reason why the module cannot connect.
Any idea on how to fix this?

**Comment by miesli** [comment] 2020-12-16 15:34
I got the same error while trying to set up a new mopidy session today. Seems like the new api is here to stay :/

**Comment by pfpmeijers** [comment] 2020-12-16 16:40
I patched the /usr/local/lib/python3.7/dist-packages/mopidy_radionet/radionet.py file to hardcode the apiPrefix as "https://api.radio.net/info/v2" and then it works again. Maybe a hardcoded prefix is as robust as trying retrieve it from the main radio.net page (base url).

Inserted line 79:
        apiprefix_search = re.search('apiPrefix ?: ?\'(.*)\',?', tmp_str.content.decode())
        self.api_prefix = apiprefix_search.group(1)
        self.api_prefix = "https://api.radio.net/info/v2"

**Comment by gemolnar79** [comment] 2020-12-16 19:21
Thanks for the quick fix. Confirmed, it works again.

**Comment by plintx** [comment] 2020-12-22 14:09
Merged, can I close this issue or the problem still exists?

**Comment by pfpmeijers** [comment] 2020-12-22 19:40
Problem is gone for me. Its working.

**Closed as completed** 2020-12-22 20:15 UTC
